version: 2.1
executors:
  docker-executor:
    docker:
      - image: cypress/browsers:node16.3.0-chrome91-ff89

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm test

  performance_test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run Performance Test
          command: |
            npm install lighthouse
            node tests/performance-test.js

  cypress_test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Run Cypress Tests
          command: |
            npm install cypress
            $(npm bin)/cypress run --config-file cypress.config.js --spec cypress/e2e/watchlist.spec.cy.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - performance_test
      - cypress_test









