version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t jeancarloshm/frame-app .

  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Test Docker Image
          command: |
            docker run jeancarloshm/frame-app npm test

  cypress_test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Run Cypress Tests
          command: |
            docker run -v $PWD:/app -w /app -e CYPRESS_baseUrl=http://localhost:3000 cypress/included:8.3.0 run --spec cypress/e2e/watchlist.spec.cy.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - cypress_test




