version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker Image
          command: docker build -t jeancarloshm/frame-app .

  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Test Docker Image
          command: |
            docker run jeancarloshm/frame-app npm test

  watchlist_test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Run Watchlist Test
          command: |
            docker run jeancarloshm/frame-app npm run test:watchlist

